name: verified
description: Instantly confirm the legitimacy of personal information with our user-friendly app. Ensure accuracy and trust in your data effortlessly.
publish_to: "none" 
version: 1.2.46+12

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  google_fonts: ^6.2.1
  currency_text_input_formatter: ^2.1.10
  confetti: ^0.7.0
  flutter_polygon: ^0.3.0+2
  get_it: ^8.0.0
  auto_route: ^9.2.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  flutter_js: ^0.8.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_auth_platform_interface: 
  flutter_overlay_loader: ^2.0.0
  http: ^1.1.0
  restart_app: ^1.2.1
  sliver_tools: ^0.2.12
  easy_rich_text: ^2.1.0
  rsa_id_number: ^1.0.2
  gallery_asset_picker: 
    git:
      url: https://github.com/makhosi6/gallery_asset_picker.git
      ref: ed56d6bc3749e4f0ce576e61e533f2a973a5ec62
  fluttertoast: ^8.2.4
  package_info_plus: ^8.0.2
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.2.3
  rxdart: ^0.28.0
  flutter_native_splash: ^2.3.7
  flutter_image_compress: ^2.2.0
  image: ^4.1.7
  path_provider: ^2.1.2
  string_scanner: ^1.2.0
  vibration: ^2.0.0
  device_info_plus: ^10.1.2
  lottie: ^3.1.2
  carousel_indicator: ^1.0.6
  skeletonizer: ^1.0.1
  app_links: ^6.3.2
  uuid: ^4.0.0
  appscheme: 
    git: 
      url: https://github.com/makhosi6/flutter-scheme.git
      ref: fix/remove-namespace
  camera: ^0.10.5+9
  flutter_beep: ^1.0.0
  face_camera:
    git:
      url: https://github.com/makhosi6/face_camera.git
      ref: feature/verified
  flutter_mrz_scanner: ^2.1.0
  google_mlkit_face_detection: 0.11.0
  google_mlkit_barcode_scanning: 0.12.0
  google_mlkit_text_recognition: 0.13.0
  mrz_parser: ^2.0.0
  firebase_crashlytics: ^3.5.7
  firebase_analytics: ^10.10.7
  flutter_signature_pad: ^3.0.1
  hand_signature: ^3.0.3
  syncfusion_flutter_signaturepad: ^27.1.51
  file_picker: ^8.1.2
  material_dialogs: ^1.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.4.2
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
  integration_test:
    sdk: flutter

dependency_overrides:
      win32: ^5.5.4
      archive: ^3.6.1
      google_mlkit_commons: 0.7.0

flutter:
  fonts:
      - family: SWFont
        fonts:
          - asset: "assets/fonts/helveticaNeue/Helvetica-Neu-Bold.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-BlackCond.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Light.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Medium.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Thin.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Bold.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Regular.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueHv.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueIt.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueLt.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueMed.ttf"
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/gif/
    - server/