name: verified
description: Instantly confirm the legitimacy of personal information with our user-friendly app. Ensure accuracy and trust in your data effortlessly.
publish_to: "none" 
version: 1.1.37+6

environment:
  sdk: ">=3.0.0 <4.0.0"

flutter_native_splash:
  color: "ed2939"
  image: assets/images/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  google_fonts: ^5.1.0
  currency_text_input_formatter: ^2.1.10
  confetti: ^0.7.0
  flutter_polygon: ^0.3.0+2
  get_it: ^7.6.4
  auto_route: ^7.8.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  flutter_js: ^0.8.0
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0
  firebase_auth_platform_interface: 
  flutter_overlay_loader: ^2.0.0
  http: ^1.1.0
  restart_app: ^1.2.1
  sliver_tools: ^0.2.12
  easy_rich_text: ^2.1.0
  rsa_id_number: ^0.1.8
  gallery_asset_picker: ^0.0.4
  fluttertoast: ^8.2.4
  uuid: ^3.0.7
  package_info_plus: ^4.2.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2
  rxdart: ^0.27.7
  flutter_native_splash: ^2.3.7
  flutter_image_compress: ^2.2.0
  image: ^4.1.7
  path_provider: ^2.1.2
  string_scanner: ^1.2.0
  vibration: ^1.8.4
  device_info_plus: ^9.1.2
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed: ^2.4.2
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter

flutter:
  fonts:
      - family: SWFont
        fonts:
          - asset: "assets/fonts/helveticaNeue/Helvetica-Neu-Bold.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-BlackCond.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Light.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Medium.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Thin.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Bold.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeue-Regular.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueHv.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueIt.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueLt.ttf"
          - asset: "assets/fonts/helveticaNeue/HelveticaNeueMed.ttf"
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - server/