// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9eWEQqpKLzX6-swpWtICq8KB3sTGE86M',
    appId: '1:59242207359:web:f5bdaf4afeb99d00ff874a',
    messagingSenderId: '59242207359',
    projectId: 'verified-b3621',
    authDomain: 'verified-b3621.firebaseapp.com',
    storageBucket: 'verified-b3621.appspot.com',
    measurementId: 'G-MECPDEDKH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKJYDrUDb9EqDU0vgH7E_xAtWr8cGUKno',
    appId: '1:59242207359:android:743ddcd6b93ceed7ff874a',
    messagingSenderId: '59242207359',
    projectId: 'verified-b3621',
    storageBucket: 'verified-b3621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAws0-4rhq20sN-03Jzzqrjf0gNfIKipCY',
    appId: '1:59242207359:ios:8e9fbd18f9f42545ff874a',
    messagingSenderId: '59242207359',
    projectId: 'verified-b3621',
    storageBucket: 'verified-b3621.appspot.com',
    iosBundleId: 'com.byteestudio.Verified',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAws0-4rhq20sN-03Jzzqrjf0gNfIKipCY',
    appId: '1:59242207359:ios:57e977754c58595cff874a',
    messagingSenderId: '59242207359',
    projectId: 'verified-b3621',
    storageBucket: 'verified-b3621.appspot.com',
    iosBundleId: 'com.byteestudio.Verified.RunnerTests',
  );
}
