// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRZ9SFStX3ukcivSg8gScJSTz7lewyMP4',
    appId: '1:683016435808:web:0f6573b940e8f1699e6b05',
    messagingSenderId: '683016435808',
    projectId: 'verified-35ca4',
    authDomain: 'verified-35ca4.firebaseapp.com',
    storageBucket: 'verified-35ca4.appspot.com',
    measurementId: 'G-4S2T2TX97S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKxRh2Ne3FFBJAOdXa6OX74u6sgl3MwQ',
    appId: '1:683016435808:android:df6237e38721b2c19e6b05',
    messagingSenderId: '683016435808',
    projectId: 'verified-35ca4',
    storageBucket: 'verified-35ca4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ3eODCku5id7clwaYRGN9E8hzY1MVpd0',
    appId: '1:683016435808:ios:e783acd946bbc12e9e6b05',
    messagingSenderId: '683016435808',
    projectId: 'verified-35ca4',
    storageBucket: 'verified-35ca4.appspot.com',
    iosClientId: '683016435808-otsnec9ih16qgkdgtdi5gma0uci7dnuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.verifySa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ3eODCku5id7clwaYRGN9E8hzY1MVpd0',
    appId: '1:683016435808:ios:918fd4ae11a8dc629e6b05',
    messagingSenderId: '683016435808',
    projectId: 'verified-35ca4',
    storageBucket: 'verified-35ca4.appspot.com',
    iosClientId: '683016435808-lcdq9am38muc52va7mv9c932tclv0s4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.verifySa.RunnerTests',
  );
}
