// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-9XtkaXL28sY_zBZyc4aVk0zMmDnC90',
    appId: '1:444267806901:web:397e7bef121d27beddbefc',
    messagingSenderId: '444267806901',
    projectId: 'verifiedapp-73c16',
    authDomain: 'verifiedapp-73c16.firebaseapp.com',
    storageBucket: 'verifiedapp-73c16.firebasestorage.app',
    measurementId: 'G-03KRPT4LF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTyl1cZO4_0ZVRZNRuFWhnkG8VOx594MM',
    appId: '1:444267806901:android:464410b1ba2416f5ddbefc',
    messagingSenderId: '444267806901',
    projectId: 'verifiedapp-73c16',
    storageBucket: 'verifiedapp-73c16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqMrqZed-F_U4c24QzGVxL7evU42NsZXg',
    appId: '1:444267806901:ios:1432e4f82812336fddbefc',
    messagingSenderId: '444267806901',
    projectId: 'verifiedapp-73c16',
    storageBucket: 'verifiedapp-73c16.firebasestorage.app',
    androidClientId: '444267806901-cttgs0cdjrtj6n44dk4gee466e178598.apps.googleusercontent.com',
    iosClientId: '444267806901-ngqosb35unq1hjeoaberkbembbheo8fv.apps.googleusercontent.com',
    iosBundleId: 'com.byteestudio.Verified',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqMrqZed-F_U4c24QzGVxL7evU42NsZXg',
    appId: '1:444267806901:ios:1432e4f82812336fddbefc',
    messagingSenderId: '444267806901',
    projectId: 'verifiedapp-73c16',
    storageBucket: 'verifiedapp-73c16.firebasestorage.app',
    androidClientId: '444267806901-cttgs0cdjrtj6n44dk4gee466e178598.apps.googleusercontent.com',
    iosClientId: '444267806901-ngqosb35unq1hjeoaberkbembbheo8fv.apps.googleusercontent.com',
    iosBundleId: 'com.byteestudio.Verified',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM-9XtkaXL28sY_zBZyc4aVk0zMmDnC90',
    appId: '1:444267806901:web:397e7bef121d27beddbefc',
    messagingSenderId: '444267806901',
    projectId: 'verifiedapp-73c16',
    authDomain: 'verifiedapp-73c16.firebaseapp.com',
    storageBucket: 'verifiedapp-73c16.firebasestorage.app',
    measurementId: 'G-03KRPT4LF6',
  );
}
